language: minimal
addons:
  ssh_known_hosts: deploy.icymind.com:11235
before_install:
- openssl aes-256-cbc -K $encrypted_50185f83ff44_key -iv $encrypted_50185f83ff44_iv
  -in travis_rsa.enc -out travis_rsa -d
script: true
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 travis_rsa
- ssh-add travis_rsa
deploy:
  provider: script
  script: rsync -raz -e 'ssh -p 11235 -o StrictHostKeyChecking=no -o CheckHostIP=no'
    $TRAVIS_BUILD_DIR/index.* simon@deploy.icymind.com:/srv/www/icymind.com/
